version: '3.8'
services:
  interaction-telegram:
    build:
      context: .
    restart: always
    ports:
    - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
#    links:
#      - redis
#  redis:
#    image: "redis:alpine"
#    ports:
#      - 6378:6378
